Repository bespoke-silicon-group/basejump_stl, pull requests merged in 2021-10, with the labels that each got.

#495 Guarding initial from synthesis
  bsg_dataflow/bsg_fifo_1r1w_large.v
Labels: bug

#494 Adding declfilename waiver to bsg_defines
  bsg_misc/bsg_defines.v
Labels: enhancement

#507 Removing defines from bsg_cache_non_blocking_pkg and bsg_dmc_pkg
  bsg_cache/bsg_cache_non_blocking.v
  bsg_cache/bsg_cache_non_blocking.vh
  bsg_cache/bsg_cache_non_blocking_data_mem.v
  bsg_cache/bsg_cache_non_blocking_decode.v
  bsg_cache/bsg_cache_non_blocking_dma.v
  bsg_cache/bsg_cache_non_blocking_mhu.v
  bsg_cache/bsg_cache_non_blocking_miss_fifo.v
  bsg_cache/bsg_cache_non_blocking_pkg.v
  bsg_cache/bsg_cache_non_blocking_stat_mem.v
  bsg_cache/bsg_cache_non_blocking_tag_mem.v
  bsg_cache/bsg_cache_non_blocking_tl_stage.v
  bsg_cache/bsg_cache_to_dram_ctrl.v
  bsg_dmc/bsg_dmc.v
  bsg_dmc/bsg_dmc.vh
  bsg_dmc/bsg_dmc_controller.v
  bsg_dmc/bsg_dmc_pkg.v
  bsg_noc/bsg_mesh_router_decoder_dor.v
  testing/bsg_cache/common/bsg_nonsynth_non_blocking_dma_model.v
  testing/bsg_cache/dmc/testbench.v
  testing/bsg_cache/regression_non_blocking/basic_checker.v
  testing/bsg_cache/regression_non_blocking/block_ld_checker.v
  testing/bsg_cache/regression_non_blocking/cov_mhu.v
  testing/bsg_cache/regression_non_blocking/cov_miss_fifo.v
  testing/bsg_cache/regression_non_blocking/cov_tl_stage.v
  testing/bsg_cache/regression_non_blocking/tag_checker.v
  testing/bsg_cache/regression_non_blocking/testbench.v
  testing/bsg_dmc/testbench.v
Labels: clarity

#502 Latchfile negphase
  bsg_mem/bsg_mem_multiport_latch.v
  bsg_mem/bsg_mem_multiport_latch_write_banked_bypassing.v
  bsg_mem/bsg_mem_multiport_latch_write_banked_bypassing_sync.v
  bsg_misc/bsg_icg_neg.v
  bsg_misc/bsg_icg_pos.v
Labels: WIP
